# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foperation.proto\x12\x08\x63ontract\"P\n\x15QueryExecutionRequest\x12\x14\n\x0clogical_plan\x18\x01 \x01(\t\x12\x15\n\rsql_statement\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"\\\n\x16QueryExecutionResponse\x12\x16\n\x0es3_result_link\x18\x01 \x01(\t\x12*\n\nerror_type\x18\x02 \x01(\x0b\x32\x16.contract.ErrorDetails\"J\n\x0c\x45rrorDetails\x12)\n\nerror_type\x18\x01 \x01(\x0e\x32\x15.contract.returnTypes\x12\x0f\n\x07message\x18\x02 \x01(\t*\x8a\x01\n\x0breturnTypes\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0f\n\x0bPARSE_ERROR\x10\x01\x12\x13\n\x0f\x45XECUTION_ERROR\x10\x02\x12\x10\n\x0cSOURCE_ERROR\x10\x03\x12\x10\n\x0cUPLOAD_ERROR\x10\x04\x12\x11\n\rOUT_OF_MEMORY\x10\x05\x12\x11\n\rUNKNOWN_ERROR\x10\x06\x32`\n\x0bSSOperation\x12Q\n\x0c\x45xecuteQuery\x12\x1f.contract.QueryExecutionRequest\x1a .contract.QueryExecutionResponseB+Z)opti-sql-go/Backend/opti-sql-go/substraitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)opti-sql-go/Backend/opti-sql-go/substrait'
  _globals['_RETURNTYPES']._serialized_start=282
  _globals['_RETURNTYPES']._serialized_end=420
  _globals['_QUERYEXECUTIONREQUEST']._serialized_start=29
  _globals['_QUERYEXECUTIONREQUEST']._serialized_end=109
  _globals['_QUERYEXECUTIONRESPONSE']._serialized_start=111
  _globals['_QUERYEXECUTIONRESPONSE']._serialized_end=203
  _globals['_ERRORDETAILS']._serialized_start=205
  _globals['_ERRORDETAILS']._serialized_end=279
  _globals['_SSOPERATION']._serialized_start=422
  _globals['_SSOPERATION']._serialized_end=518
# @@protoc_insertion_point(module_scope)
