// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: operation.proto

package substrait

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnTypes int32

const (
	ReturnTypes_SUCCESS         ReturnTypes = 0
	ReturnTypes_PARSE_ERROR     ReturnTypes = 1
	ReturnTypes_EXECUTION_ERROR ReturnTypes = 2
	ReturnTypes_SOURCE_ERROR    ReturnTypes = 3
	ReturnTypes_UPLOAD_ERROR    ReturnTypes = 4
	ReturnTypes_OUT_OF_MEMORY   ReturnTypes = 5
	ReturnTypes_UNKNOWN_ERROR   ReturnTypes = 6
)

// Enum value maps for ReturnTypes.
var (
	ReturnTypes_name = map[int32]string{
		0: "SUCCESS",
		1: "PARSE_ERROR",
		2: "EXECUTION_ERROR",
		3: "SOURCE_ERROR",
		4: "UPLOAD_ERROR",
		5: "OUT_OF_MEMORY",
		6: "UNKNOWN_ERROR",
	}
	ReturnTypes_value = map[string]int32{
		"SUCCESS":         0,
		"PARSE_ERROR":     1,
		"EXECUTION_ERROR": 2,
		"SOURCE_ERROR":    3,
		"UPLOAD_ERROR":    4,
		"OUT_OF_MEMORY":   5,
		"UNKNOWN_ERROR":   6,
	}
)

func (x ReturnTypes) Enum() *ReturnTypes {
	p := new(ReturnTypes)
	*p = x
	return p
}

func (x ReturnTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_operation_proto_enumTypes[0].Descriptor()
}

func (ReturnTypes) Type() protoreflect.EnumType {
	return &file_operation_proto_enumTypes[0]
}

func (x ReturnTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnTypes.Descriptor instead.
func (ReturnTypes) EnumDescriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{0}
}

// The request message containing the operation details.
type QueryExecutionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubstraitLogical []byte                 `protobuf:"bytes,1,opt,name=substrait_logical,json=substraitLogical,proto3" json:"substrait_logical,omitempty"` //SS logical plan
	SqlStatement     string                 `protobuf:"bytes,2,opt,name=sql_statement,json=sqlStatement,proto3" json:"sql_statement,omitempty"`             // original sql statement
	Id               string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                                                     // unique id for this client
	Source           *SourceType            `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                             // (s3 link| base64 data)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryExecutionRequest) Reset() {
	*x = QueryExecutionRequest{}
	mi := &file_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecutionRequest) ProtoMessage() {}

func (x *QueryExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecutionRequest.ProtoReflect.Descriptor instead.
func (*QueryExecutionRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{0}
}

func (x *QueryExecutionRequest) GetSubstraitLogical() []byte {
	if x != nil {
		return x.SubstraitLogical
	}
	return nil
}

func (x *QueryExecutionRequest) GetSqlStatement() string {
	if x != nil {
		return x.SqlStatement
	}
	return ""
}

func (x *QueryExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryExecutionRequest) GetSource() *SourceType {
	if x != nil {
		return x.Source
	}
	return nil
}

// The response message containing the result.
type QueryExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3ResultLink  string                 `protobuf:"bytes,1,opt,name=s3_result_link,json=s3ResultLink,proto3" json:"s3_result_link,omitempty"` // s3 link to the result data
	ErrorType     *ErrorDetails          `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`            // error type if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExecutionResponse) Reset() {
	*x = QueryExecutionResponse{}
	mi := &file_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecutionResponse) ProtoMessage() {}

func (x *QueryExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecutionResponse.ProtoReflect.Descriptor instead.
func (*QueryExecutionResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{1}
}

func (x *QueryExecutionResponse) GetS3ResultLink() string {
	if x != nil {
		return x.S3ResultLink
	}
	return ""
}

func (x *QueryExecutionResponse) GetErrorType() *ErrorDetails {
	if x != nil {
		return x.ErrorType
	}
	return nil
}

type SourceType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Source      string                 `protobuf:"bytes,1,opt,name=s3_source,json=s3Source,proto3" json:"s3_source,omitempty"` // s3 link to the source data
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceType) Reset() {
	*x = SourceType{}
	mi := &file_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceType) ProtoMessage() {}

func (x *SourceType) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceType.ProtoReflect.Descriptor instead.
func (*SourceType) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{2}
}

func (x *SourceType) GetS3Source() string {
	if x != nil {
		return x.S3Source
	}
	return ""
}

func (x *SourceType) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorType     ReturnTypes            `protobuf:"varint,1,opt,name=error_type,json=errorType,proto3,enum=contract.ReturnTypes" json:"error_type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetails) GetErrorType() ReturnTypes {
	if x != nil {
		return x.ErrorType
	}
	return ReturnTypes_SUCCESS
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_operation_proto protoreflect.FileDescriptor

const file_operation_proto_rawDesc = "" +
	"\n" +
	"\x0foperation.proto\x12\bcontract\"\xa7\x01\n" +
	"\x15QueryExecutionRequest\x12+\n" +
	"\x11substrait_logical\x18\x01 \x01(\fR\x10substraitLogical\x12#\n" +
	"\rsql_statement\x18\x02 \x01(\tR\fsqlStatement\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12,\n" +
	"\x06source\x18\x04 \x01(\v2\x14.contract.SourceTypeR\x06source\"u\n" +
	"\x16QueryExecutionResponse\x12$\n" +
	"\x0es3_result_link\x18\x01 \x01(\tR\fs3ResultLink\x125\n" +
	"\n" +
	"error_type\x18\x02 \x01(\v2\x16.contract.ErrorDetailsR\terrorType\"=\n" +
	"\n" +
	"SourceType\x12\x1b\n" +
	"\ts3_source\x18\x01 \x01(\tR\bs3Source\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\"^\n" +
	"\fErrorDetails\x124\n" +
	"\n" +
	"error_type\x18\x01 \x01(\x0e2\x15.contract.returnTypesR\terrorType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8a\x01\n" +
	"\vreturnTypes\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x0f\n" +
	"\vPARSE_ERROR\x10\x01\x12\x13\n" +
	"\x0fEXECUTION_ERROR\x10\x02\x12\x10\n" +
	"\fSOURCE_ERROR\x10\x03\x12\x10\n" +
	"\fUPLOAD_ERROR\x10\x04\x12\x11\n" +
	"\rOUT_OF_MEMORY\x10\x05\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x062`\n" +
	"\vSSOperation\x12Q\n" +
	"\fExecuteQuery\x12\x1f.contract.QueryExecutionRequest\x1a .contract.QueryExecutionResponseB+Z)opti-sql-go/Backend/opti-sql-go/substraitb\x06proto3"

var (
	file_operation_proto_rawDescOnce sync.Once
	file_operation_proto_rawDescData []byte
)

func file_operation_proto_rawDescGZIP() []byte {
	file_operation_proto_rawDescOnce.Do(func() {
		file_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_proto_rawDesc), len(file_operation_proto_rawDesc)))
	})
	return file_operation_proto_rawDescData
}

var file_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_operation_proto_goTypes = []any{
	(ReturnTypes)(0),               // 0: contract.returnTypes
	(*QueryExecutionRequest)(nil),  // 1: contract.QueryExecutionRequest
	(*QueryExecutionResponse)(nil), // 2: contract.QueryExecutionResponse
	(*SourceType)(nil),             // 3: contract.SourceType
	(*ErrorDetails)(nil),           // 4: contract.ErrorDetails
}
var file_operation_proto_depIdxs = []int32{
	3, // 0: contract.QueryExecutionRequest.source:type_name -> contract.SourceType
	4, // 1: contract.QueryExecutionResponse.error_type:type_name -> contract.ErrorDetails
	0, // 2: contract.ErrorDetails.error_type:type_name -> contract.returnTypes
	1, // 3: contract.SSOperation.ExecuteQuery:input_type -> contract.QueryExecutionRequest
	2, // 4: contract.SSOperation.ExecuteQuery:output_type -> contract.QueryExecutionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_operation_proto_init() }
func file_operation_proto_init() {
	if File_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_proto_rawDesc), len(file_operation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operation_proto_goTypes,
		DependencyIndexes: file_operation_proto_depIdxs,
		EnumInfos:         file_operation_proto_enumTypes,
		MessageInfos:      file_operation_proto_msgTypes,
	}.Build()
	File_operation_proto = out.File
	file_operation_proto_goTypes = nil
	file_operation_proto_depIdxs = nil
}
