// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: operation.proto

package substrait

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
//const _ = grpc.SupportPackageIsVersion9

const (
	SSOperation_ExecuteQuery_FullMethodName = "/contract.SSOperation/ExecuteQuery"
)

// SSOperationClient is the client API for SSOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition.
type SSOperationClient interface {
	ExecuteQuery(ctx context.Context, in *QueryExecutionRequest, opts ...grpc.CallOption) (*QueryExecutionResponse, error)
}

type sSOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewSSOperationClient(cc grpc.ClientConnInterface) SSOperationClient {
	return &sSOperationClient{cc}
}

func (c *sSOperationClient) ExecuteQuery(ctx context.Context, in *QueryExecutionRequest, opts ...grpc.CallOption) (*QueryExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryExecutionResponse)
	err := c.cc.Invoke(ctx, SSOperation_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSOperationServer is the server API for SSOperation service.
// All implementations must embed UnimplementedSSOperationServer
// for forward compatibility.
//
// The service definition.
type SSOperationServer interface {
	ExecuteQuery(context.Context, *QueryExecutionRequest) (*QueryExecutionResponse, error)
	mustEmbedUnimplementedSSOperationServer()
}

// UnimplementedSSOperationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSSOperationServer struct{}

func (UnimplementedSSOperationServer) ExecuteQuery(context.Context, *QueryExecutionRequest) (*QueryExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedSSOperationServer) mustEmbedUnimplementedSSOperationServer() {}
func (UnimplementedSSOperationServer) testEmbeddedByValue()                     {}

// UnsafeSSOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSOperationServer will
// result in compilation errors.
type UnsafeSSOperationServer interface {
	mustEmbedUnimplementedSSOperationServer()
}

func RegisterSSOperationServer(s grpc.ServiceRegistrar, srv SSOperationServer) {
	// If the following call pancis, it indicates UnimplementedSSOperationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SSOperation_ServiceDesc, srv)
}

func _SSOperation_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOperationServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSOperation_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOperationServer).ExecuteQuery(ctx, req.(*QueryExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SSOperation_ServiceDesc is the grpc.ServiceDesc for SSOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.SSOperation",
	HandlerType: (*SSOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _SSOperation_ExecuteQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operation.proto",
}
